stages:
  transform:
    cmd: python3 transform.py
    deps:
    - data/tested.csv
    - transform.py
    outs:
    - data/processed_data.csv
  train:
    cmd: python3 train.py
    deps:
    - data/processed_data.csv
    - train.py
    outs:
    - model/logreg_model.pkl
